#!/usr/bin/env bash
check for command line parameters

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# assigning parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# disabling stricy host key checkinh

scp -o "StrictHostKeyChecking=no" -1 "$path_to_ssh_key" "$path_to_file" "$username@ip:~/"


# checking if the tranfer was sussessful
if [ $? -eq 0 ]
then
	echo "FILE TRANFERED SUSSESSFULLY"
else
	echo "FILE TRANSFER FAILED"
fi
